export { default as Navbar } from './navbar/navbar'
export { default as SocialMedia } from './social_media/socialMedia'
export { default as Quotes } from './quotes/quotes'
export { default as TitleName } from './titleName/titleName'
export { default as Blog } from './blog/blog'
export { default as Footer } from './footer/footer'